### ISSUE TITLE
ShellExpandFailed (NameError)

### ISSUE THREAD

**Issue by eli007** [tkambler/perfect-vagrant#2]
this is with the default settings in "perfect-vagrant"

after this step:

==> api: Pruning invalid NFS exports. Administrator privileges will be required...

it errors out with this message.

/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/linux/cap/shell_expand_guest_path.rb:22:in `shell_expand_guest_path': uninitialized constant VagrantPlugins::GuestLinux::Cap::ShellExpandGuestPath::ShellExpandFailed (NameError)

is this a Vagrant issue or a way Vagrant has been configured?

**Comment by tkambler** [comment]
Check w/ Vagrant - I don't know.
